import random


def random_coordinate(domain: list[float]) -> list[float]:
    """
    Generate random `d` dimension coordinates (Random Search Heuristic)

    domain = The domain for each dimension of the coordinates to be generated
    """
    return [random.uniform(*domain[i]) for i in range(len(domain))]


def random_bitstring(size: int) -> list[int]:
    """
    Generate random bitstring as solution representation

    size = Size of the bitstring (genotype) to be generated by this function
    """
    return [random.choice((0, 1)) for _ in range(size)]
